"""add all models

Revision ID: 398a97284c7c
Revises: 
Create Date: 2024-03-14 11:40:42.422563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398a97284c7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_bot_message',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons_title',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practices',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lessons', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=False),
    sa.Column('minutes', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quited_practice',
    sa.Column('practice', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quited_workshops',
    sa.Column('workshop', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('lesson', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=False),
    sa.Column('minutes', sa.String(), nullable=False),
    sa.Column('users_number', sa.Integer(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workshops',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=False),
    sa.Column('minutes', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshops_schedule',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=False),
    sa.Column('minutes', sa.String(), nullable=False),
    sa.Column('users_number', sa.Integer(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshops_title',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshops_title')
    op.drop_table('workshops_schedule')
    op.drop_table('workshops')
    op.drop_table('users')
    op.drop_table('schedule')
    op.drop_table('quited_workshops')
    op.drop_table('quited_practice')
    op.drop_table('practices')
    op.drop_table('lessons_title')
    op.drop_table('last_bot_message')
    # ### end Alembic commands ###
