# Generated by Django 5.0.3 on 2024-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LastBotMessage",
            fields=[
                ("user_id", models.IntegerField()),
                ("message_number", models.IntegerField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "last_bot_message",
            },
        ),
        migrations.CreateModel(
            name="LessonTitle",
            fields=[
                ("title", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "lessons_title",
            },
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                ("user_id", models.IntegerField()),
                ("lessons", models.TextField()),
                ("format", models.TextField()),
                ("date", models.TextField()),
                ("hours", models.TextField()),
                ("minutes", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "practices",
            },
        ),
        migrations.CreateModel(
            name="QuitedPractice",
            fields=[
                ("practice", models.TextField()),
                ("reason", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "quited_practice",
            },
        ),
        migrations.CreateModel(
            name="QuitedWorkshop",
            fields=[
                ("workshop", models.TextField()),
                ("reason", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "quited_workshops",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("lesson", models.TextField()),
                ("format", models.TextField()),
                ("date", models.TextField()),
                ("hours", models.TextField()),
                ("minutes", models.TextField()),
                ("users_number", models.IntegerField()),
                ("additional_info", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "schedule",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("chat_id", models.IntegerField()),
                ("name", models.TextField(blank=True, null=True)),
                ("surname", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                ("user_id", models.IntegerField()),
                ("title", models.TextField()),
                ("format", models.TextField()),
                ("date", models.TextField()),
                ("hours", models.TextField()),
                ("minutes", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "workshops",
            },
        ),
        migrations.CreateModel(
            name="WorkshopsSchedule",
            fields=[
                ("title", models.TextField()),
                ("format", models.TextField()),
                ("date", models.TextField()),
                ("hours", models.TextField()),
                ("minutes", models.TextField()),
                ("users_number", models.IntegerField()),
                ("additional_info", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "workshops_schedule",
            },
        ),
        migrations.CreateModel(
            name="WorkshopTitle",
            fields=[
                ("title", models.TextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "workshops_title",
            },
        ),
    ]
