# Generated by Django 5.0.3 on 2024-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastbotmessage',
            name='message_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='lastbotmessage',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='practice',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
